import { StyleSheet } from 'react-native';
import { SPACING } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.xs,
    paddingBottom: SPACING.lg,
  },
  cameraContainer: {
    width: '100%',
    height: 320,
    backgroundColor: '#1E1E1C',
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: SPACING.md,
    position: 'relative',
  },
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  cameraToggleBtn: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  corner: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderColor: '#98C353',
    borderWidth: 2.5,
    pointerEvents: 'none',
  },
  topLeft: {
    top: 24,
    left: 24,
    borderBottomWidth: 0,
    borderRightWidth: 0,
    borderTopLeftRadius: 6,
  },
  topRight: {
    top: 24,
    right: 24,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderTopRightRadius: 6,
  },
  bottomLeft: {
    bottom: 24,
    left: 24,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomLeftRadius: 6,
  },
  bottomRight: {
    bottom: 24,
    right: 24,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderBottomRightRadius: 6,
  },
  scanLineAnim: {
    position: 'absolute',
    left: 24,
    right: 24,
    height: 2,
    backgroundColor: 'rgba(152, 195, 83, 0.8)',
    shadowColor: '#98C353',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 4,
    pointerEvents: 'none',
  },
  autoScanContainer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  spinnerCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#98C353',
    borderTopColor: 'transparent',
  },
  autoScanText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
  cameraPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 72,
    backgroundColor: '#C5C5C5',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#A8A8A8',
    borderStyle: 'dashed',
    gap: 6,
    marginBottom: SPACING.md,
  },
  uploadText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  uploadedListContainer: {
    marginBottom: SPACING.lg,
  },
  uploadedListTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333333',
    marginBottom: SPACING.sm,
  },
  uploadedList: {
    paddingBottom: 20,
  },
  uploadedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    padding: 10,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  uploadedItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  uploadedThumbnail: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  uploadedItemName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333333',
  },
  uploadedDeleteBtn: {
    padding: 8,
  },
  bottomSection: {
    paddingTop: SPACING.sm,
  },
  submitButton: {
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
  },
  toastContainer: {
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
  },
  toast: {
    backgroundColor: 'rgba(71, 92, 58, 0.9)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  toastText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
});

export default styles;
